imports:
  - { resource: parameters.yml }
  - { resource: services.yml }

parameters:
  locale: en
  container.autowiring.strict_mode: true

twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

framework:
  php_errors:
    log: true
  secret: goii0sfg32423479234ß98203466dd
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  http_client:
    scoped_clients:
      jasper.client:
        auth_basic: "jasperadmin:jasperadmin"
        base_uri: "http://172.22.51.41:8080/jasperserver-pro/rest_v2/"
